# Generated by Django 5.2.11 on 2026-03-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_location_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Нет значения', max_length=255),
        ),
    ]
