# Generated by Django 5.2.11 on 2026-04-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_jobs_job_title_0e1e41_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
    ]
