# Generated by Django 5.2.11 on 2026-04-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
    ]
